// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/pluckhuang/goweb/aweb/follow/grpc"
	"github.com/pluckhuang/goweb/aweb/follow/ioc"
	"github.com/pluckhuang/goweb/aweb/follow/repository"
	"github.com/pluckhuang/goweb/aweb/follow/repository/cache"
	"github.com/pluckhuang/goweb/aweb/follow/repository/dao"
	"github.com/pluckhuang/goweb/aweb/follow/service"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	db := ioc.InitDB(loggerV1)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, loggerV1)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	server := ioc.InitGRPCxServer(loggerV1, client, followServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, cache.NewRedisFollowCache, repository.NewFollowRelationRepository, service.NewFollowRelationService, grpc.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitDB, ioc.InitEtcdClient, ioc.InitLogger)
