// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/pluckhuang/goweb/aweb/feed/events"
	"github.com/pluckhuang/goweb/aweb/feed/grpc"
	"github.com/pluckhuang/goweb/aweb/feed/ioc"
	"github.com/pluckhuang/goweb/aweb/feed/repository"
	"github.com/pluckhuang/goweb/aweb/feed/repository/dao"
	"github.com/pluckhuang/goweb/aweb/feed/service"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	db := ioc.InitDB(loggerV1)
	feedPullEventDAO := dao.NewFeedPullEventDAO(db)
	feedPushEventDAO := dao.NewFeedPushEventDAO(db)
	feedEventRepo := repository.NewFeedEventRepo(feedPullEventDAO, feedPushEventDAO)
	followServiceClient := ioc.InitFollowClient()
	articleEventConfig := ioc.InitGlobalVal()
	v := ioc.RegisterHandler(feedEventRepo, followServiceClient, articleEventConfig)
	feedService := service.NewFeedService(feedEventRepo, v)
	feedEventGrpcSvc := grpc.NewFeedEventGrpcSvc(feedService)
	server := ioc.InitGRPCxServer(loggerV1, client, feedEventGrpcSvc)
	saramaClient := ioc.InitKafka()
	feedEventConsumer := events.NewFeedEventConsumer(saramaClient, loggerV1, feedService)
	v2 := ioc.InitConsumers(feedEventConsumer)
	app := &App{
		server:    server,
		consumers: v2,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewFeedPushEventDAO, dao.NewFeedPullEventDAO, repository.NewFeedEventRepo)

var thirdProvider = wire.NewSet(ioc.InitEtcdClient, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka, ioc.InitDB, ioc.InitFollowClient, ioc.InitGlobalVal)
