// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/pluckhuang/goweb/oauth2/grpc"
	"github.com/pluckhuang/goweb/oauth2/ioc"
	"github.com/pluckhuang/goweb/oauth2/service"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	cmdable := ioc.InitRedis()
	v := ioc.InitService(cmdable, loggerV1)
	oauth2Service := service.NewOauth2Service(v)
	oauth2ServiceServer := grpc.NewOauth2ServiceServer(oauth2Service)
	server := ioc.InitGRPCxServer(loggerV1, client, oauth2ServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitEtcdClient, ioc.InitRedis, ioc.InitLogger)
