db:
  dsn: "root:password@tcp(localhost:13306)/aweb"

grpc:
  server:
    port: "8075"
    etcdTTL: 60

etcd:
  endpoints:
    - "localhost:12379"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

es:
  urls: "https://localhost:9200"
  sniff: false
