db:
  dsn: "root:password@tcp(localhost:13306)/aweb"

grpc:
  server:
    port: "8076"
    etcdTTL: 60
  client:
    article:
      target: “etcd:///service/ArticleService”

etcd:
  endpoints:
    - "localhost:12379"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"
