db:
  dsn: "root:password@tcp(localhost:13306)/aweb"
grpc:
  server:
    addr: "8081"
    etcdTTL: 60
  client:
    follow:
      target: "etcd:///service/FollowService"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"
kafka:
  addrs:
    - "localhost:9094"

service:
  threshold: 4
