// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/pluckhuang/goweb/aweb/interactive/events"
	"github.com/pluckhuang/goweb/aweb/interactive/grpc"
	"github.com/pluckhuang/goweb/aweb/interactive/ioc"
	"github.com/pluckhuang/goweb/aweb/interactive/repository"
	"github.com/pluckhuang/goweb/aweb/interactive/repository/cache"
	"github.com/pluckhuang/goweb/aweb/interactive/repository/dao"
	"github.com/pluckhuang/goweb/aweb/interactive/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitSaramaClient()
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, loggerV1, interactiveCache)
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(client, loggerV1, interactiveRepository)
	interactiveSyncEventConsumer := events.NewInteractiveSyncEventConsumer(client, loggerV1, interactiveRepository)
	v := ioc.InitConsumers(interactiveReadEventConsumer, interactiveSyncEventConsumer)
	clientv3Client := ioc.InitEtcdClient()
	syncProducer := ioc.InitSaramaSyncProducer(client)
	interactiveProducer := events.NewInteractiveProducer(syncProducer)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1, interactiveProducer)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServer(loggerV1, clientv3Client, interactiveServiceServer)
	app := &App{
		consumers: v,
		server:    server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient, ioc.InitSaramaClient, ioc.InitSaramaSyncProducer, ioc.InitRedis)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, events.NewInteractiveProducer, service.NewInteractiveService)
